const carName = 'Volvo';
const years = 50;
const x = 5;
const y = 10;
console.log(x + y);
const z = x + y;
console.log(z);
const firstName = "John", lastName = "Doe", age = 35;
const a = 10;
const b = 5;
console.log(a * b);